name: Build PyCoral

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_pycoral:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11 environment
      uses: actions/setup-python@v5  # Ensures Python 3.11 is installed
      with:
        python-version: '3.11'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Additional Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential cmake git wget libusb-1.0-0-dev libssl-dev

    - name: Clone and Prepare PyCoral
      run: |
        git clone --recurse-submodules https://github.com/google-coral/pycoral --depth 1
        cd pycoral
        # Patch any unsupported compiler flags if needed
        find . -type f \( -name "BUILD.bazel" -o -name "*.bzl" -o -name "*.c" \) -exec sed -i 's/-std=c++14//g' {} +
        # Clean Bazel cache
        bazel clean --expunge

    - name: Build PyCoral
      run: |
        cd pycoral
        # Build PyCoral using Bazel
        sudo bash scripts/build.sh  # Ensures the script has the right permissions
        make wheel  # Build the Python wheel for PyCoral
        python -m pip install $(ls dist/*.whl)  # Install the wheel to verify

    - name: Upload PyCoral artifact
      uses: actions/upload-artifact@v3
      with:
        name: pycoral-build-artifact
        path: pycoral/dist/*
