name: Build and Upload PyCoral Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential cmake git wget libusb-1.0-0-dev libssl-dev

    - name: Install Python Dependencies
      run: |
        source venv/bin/activate
        pip install numpy tensorflow

    - name: Debug Build Environment
      run: |
        source venv/bin/activate
        python -m pip list
        gcc --version
        # Add more debug commands if needed

    - name: Build PyCoral
      run: |
        set -x  # Enable debug mode to print commands
        source venv/bin/activate
        git clone --recurse-submodules https://github.com/google-coral/pycoral --depth 1
        cd pycoral
        sudo bash scripts/build.sh
        make wheel
        python -m pip install $(ls dist/*.whl)

    - name: Upload PyCoral Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pycoral-build-artifact
        path: pycoral/dist/*
