name: Build and Upload PyCoral Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        venv/bin/python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential cmake git wget libusb-1.0-0-dev libssl-dev

    - name: Install Python Dependencies
      run: |
        venv/bin/pip install numpy tensorflow  # Install directly using venv's pip

    - name: Debug Build Environment
      run: |
        venv/bin/pip list  # List installed Python packages
        gcc --version  # Show GCC version
        cmake --version  # Show CMake version

    - name: Build PyCoral
      run: |
        set -x  # Enable debug mode to print commands
        git clone --recurse-submodules https://github.com/google-coral/pycoral --depth 1
        cd pycoral
        bash scripts/build.sh  # No need for sudo; run build script directly
        make wheel
        venv/bin/pip install $(ls dist/*.whl)  # Install using venv's pip

    - name: Upload PyCoral Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pycoral-build-artifact
        path: pycoral/dist/*
