name: Build libedgetpu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_libedgetpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11 environment
      uses: actions/setup-python@v5  # Ensures Python 3.11 is installed
      with:
        python-version: '3.11'

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Clone and Build libedgetpu
      run: |
        git clone https://github.com/google-coral/libedgetpu.git
        cd libedgetpu
        # Patch unsupported flags
        find . -type f \( -name "BUILD.bazel" -o -name "*.bzl" -o -name "*.c" \) -exec sed -i 's/-mavx512fp16/-mavx512bf16/g' {} +
        # Build libedgetpu
        bazel build --cxxopt='-std=c++17' --sandbox_debug --verbose_failures //tflite/public:libedgetpu_direct_all.so.stripped
        sudo cp bazel-bin/tflite/public/libedgetpu_direct_all.so /usr/lib/x86_64-linux-gnu/
        sudo ldconfig

    - name: Upload libedgetpu artifact
      uses: actions/upload-artifact@v3
      with:
        name: libedgetpu-build-artifact
        path: libedgetpu/out/direct/k8/*
