name: Build and Test libedgetpu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_libedgetpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install GCC-11
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install gcc-11 g++-11 -y
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11

    - name: Verify GCC version
      run: |
        gcc --version

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Additional Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git wget libusb-1.0-0-dev libssl-dev

    - name: Clone and Prepare libedgetpu
      run: |
        git clone https://github.com/google-coral/libedgetpu.git
        cd libedgetpu
        # Optionally modify or configure files as needed
        # Clean Bazel cache to prevent issues from previous builds
        bazel clean --expunge

    - name: Build libedgetpu
      run: |
        cd libedgetpu
        bazel build --compiler=gcc-11 --spawn_strategy=local --jobs=1 --cxxopt='-std=c++17' --sandbox_debug --verbose_failures //tflite/public:libedgetpu_direct_all.so.stripped

    - name: Upload libedgetpu artifact
      uses: actions/upload-artifact@v3
      with:
        name: libedgetpu-build-artifact
        path: libedgetpu/bazel-bin/tflite/public/*.so
