name: Build Coral Edge TPU Components with TensorFlow 2.17.0 and NumPy 2.0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 for node20 compatibility

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential cmake git wget python3.11 python3.11-dev python3.11-venv python3-pip

    - name: Install libusb development files
      run: |
        sudo apt-get install -y libusb-1.0-0-dev

    - name: Install Bazel
      run: |
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
        echo "deb [signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update && sudo apt-get install -y bazel

    - name: Set up Python 3.11
      uses: actions/setup-python@v5  # Updated to v5 for node20 compatibility
      with:
        python-version: '3.11'

    - name: Install TensorFlow 2.17.0 and NumPy 2.0
      run: |
        python3.11 -m pip install tensorflow==2.17.0
        python3.11 -m pip install numpy==2.0.0

    - name: Install Additional Dependencies (Pandas, Matplotlib, SciPy, etc.)
      run: |
        python3.11 -m pip install pandas matplotlib scipy scikit-learn

    - name: Build libedgetpu with XNNPACK Patch
      run: |
        git clone https://github.com/google-coral/libedgetpu.git
        cd libedgetpu
        # Clean Bazel cache
        bazel clean --expunge  
        # Run Bazel to download all dependencies without building
        bazel fetch //tflite/public:libedgetpu_direct_all.so.stripped
        # Find and patch all instances of the unsupported flag in the Bazel build files
        find . -type f -name "BUILD.bazel" -exec sed -i 's/-mavx512fp16/-mavx512bf16/g' {} +
        # Build libedgetpu with patched XNNPACK configuration
        bazel build --cxxopt='-std=c++17' --sandbox_debug --verbose_failures //tflite/public:libedgetpu_direct_all.so.stripped
        sudo cp bazel-bin/tflite/public/libedgetpu_direct_all.so /usr/lib/x86_64-linux-gnu/
        sudo ldconfig

    - name: Build TensorFlow Lite Runtime with TensorFlow 2.17.0
      run: |
        git clone https://github.com/tensorflow/tensorflow.git
        cd tensorflow
        git checkout v2.17.0  # Ensure matching TensorFlow version
        ./tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
        python3.11 -m pip install tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-*.whl

    - name: Build PyCoral with TensorFlow 2.17.0
      run: |
        git clone --recurse-submodules https://github.com/google-coral/pycoral --depth 1
        cd pycoral
        # Ensure the build script uses TensorFlow 2.17.0
        sudo bash scripts/build.sh
        make wheel
        python3.11 -m pip install $(ls dist/*.whl)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coral-build-artifacts
        path: |
          libedgetpu/out/direct/k8/*
          tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/*
          pycoral/dist/*.whl
